#!/usr/bin/env python
# coding: utf-8

# ## **Getting Started with eBay's APIs** 
# 
# In this chapter, we will be giving an overview of accessing eBay’s API through their <a href="https://developer.ebay.com/ ">developer’s program</a>. This chapter will be more theoretical in understanding the specific APIs by eBay, and what features you can find within these APIs compared to chapter 3. We will also give an overview of the different steps we implemented to access eBay’s API. Once access is granted, there are many different APIs available, so we will be condensing this information to be relevant for the scope of this project. 
# 
# ### **Documentation of eBay's APIs** 
# 
# eBay has different APIs to access various listings features. These features can be understood by the characteristics of a given item posting such as the given item or product, description, price, buying, delivery options, etc. eBay stores the information of the various post characteristics in different APIs in their documentation. The documentation on eBay’s developer’s program is fairly comprehensive, but we will condense that information to make it relevant to this project. Please note that the documentation is vast and changes on occasion, so it is best to cross reference information when something does not seem right. 
# 

# ### **Understanding the different types of eBay's APIs** 
# 
# In order to account for the variety of users that use eBay’s developer’s program, eBay has many APIs that access different aspects of listings and marketplaces. By using an API, eBay can keep track of who is using their data and for what purposes. When we use an API, we are keeping in accordance with their data governance while having a streamlined process of accessing data. While there is room to explore eBay’s different APIs further, to find the variables of interest for our project, we used two APIs: the Shopping API and the Finding API. We used two APIs, as different variables of interest could be extracted from the Finding and Shopping API. First, we used the Finding API to filter across categories of interest in a specific timeframe. Next, we will use the Shopping API to go through the items extracted from the Finding API to find other variables of interest for specific listings. The details of the implementation for our specific use-case are in the following subsections.  
# 
# ### **Finding API and Shopping API** 
# 
# The <a href="https://developer.ebay.com/devzone/finding/CallRef/index.html" 
# target="_blank">Finding API</a> is the first API we access to gather some of the features of interest for the scope of the project. We used the Finding API to search for items posted on the platform. Different calls are ways in which you can gather the data based on certain parameters. In the table below, various types of calls from the Finding API are discussed. The table summarizes the type of call, its description, and links where users can access complementary information.
# 
# The goal of our project is to find illicit listings based on certain categories of interest that are pre-decided from discussion with stakeholders. In the Categories section of this chapter, we discuss how we came about deciding on categories of interest to input as a parameter of the <code>findItemsbyCategory</code> call under the Finding API. In this project, we decided to use the <code>findItems</code> by Category call because the goal in data collection is to get data on categories where illicit items might be listed under. Categories are structures organized in a hierarchical form composed of sheets containing listings. For example, eBay shopping uses <code>GetCategoryInfo</code> to search for information about the names and IDs of a product.
# 
# *Table 3.* Finding API Calls with examples: 
# 
# |     Call                                                                                                                                                                   |     Summary                                                                                                                                                                       |
# |----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
# |     <a href="https://developer.ebay.com/devzone/finding/CallRef/findItemsAdvanced.html"><code>findItemsAdvanced</code></a>                                                 |     Searches for items by   category or keyword or both .                                                                                                                         |
# |           <a href="https://developer.ebay.com/devzone/finding/CallRef/findItemsByCategory.html">**<code>findItemsByCategory</code>**</a>                                   |     Finds items in a specific eBay category Id numbers.                                                                                                                           |
# |           <a href="https://developer.ebay.com/devzone/finding/CallRef/findItemsByKeywords.html"><code>findItemsByKeywords</code></a>                                       |     Finds items by a keyword   query and provides details by matching the search criteria.                                                                                        |
# |     <a href="https://developer.ebay.com/devzone/finding/CallRef/findItemsByProduct.html "><code>findItemsByProduct</code></a>                                              |     Gets items based on a   product ID, i.e., ISBN.                                                                                                                               |
# |     <a href="https://developer.ebay.com/devzone/finding/CallRef/findItemsIneBayStores.html "><code>findItemsIneBayStores</code></a>                                        |     Searches for items in the   eBay store inventories. Users can combine storeName with keywords, or use   keywords without storeName to search for items in all eBay stores.    |
# |     <a href="https://developer.ebay.com/devzone/finding/CallRef/getHistograms.html"><code>getHistograms</code></a>                                                         |     Gets categories and/or   aspect histogram information for eBay’s categories.                                                                                                  |
# |     <a href="https://developer.ebay.com/devzone/finding/CallRef/getSearchKeywordsRecommendation.html     "><code>getSearchKeywordsRecommendation</code></a>                |     Gets   specified keywords and returns correctly spelled keywords for best search   results.                                                                                   |
# |     <a href="https://developer.ebay.com/devzone/finding/CallRef/getVersion.html "><code>getVersion</code></a>                                                              |     Provides information about   the current version of the service                                                                                                               |
# 
# By using the <code>findItemsbyCategory</code> under the Finding API, users can get various variables of interest (output) including item ID, product title, country, price, and postal code. This implementation can be seen in the chapter “Navigating the Code”. We picked this call and corresponding API, because this project aims to quantify the illicit cultural trade industry. By collecting data on these variables, we are able to identify unique listings and what the object is. While the variables from this API are insightful, there are some missing gaps for data that this project is interested in. A unique seller identifier and other information about the details of the object cannot be found in this API. Thus, we use the<a href="https://developer.ebay.com/DevZone/shopping/docs/CallRef/index.html" target="_blank">Shopping API</a> to get more corresponding data to the listings extracted from the Finding API. Details about feature specifics are in our data description section. 
# 
# 
# *Table 4.* Shopping API Calls with examples:
# 
# |     Call                                                                                                                                              	|     Summary                                                                                                                                                                                                     	|
# |-------------------------------------------------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
# |     <a href=" https://developer.ebay.com/DevZone/shopping/docs/CallRef/FindProducts.html "><code>FindProducts</code></a>                              	|     Supports shopping   comparisons of products by passing in keywords (related to the item) and   retrieving product titles, descriptions, and/or items specifics.                                             	|
# |     <a href=" https://developer.ebay.com/DevZone/shopping/docs/CallRef/GetCategoryInfo.html"><code>   GetCategoryInfo </code></a>                     	|     Retrieves information for a   specified category, including name, ID value, and other names and category   IDs of the product. Also, it includes the version number and its last update   of a category.    	|
# |     <a href=" https://developer.ebay.com/DevZone/shopping/docs/CallRef/GeteBayTime.html"><code>GeteBayTime</code></a>                                 	|     Returns the date and time   of a processed request in Greenwich    Mean Time (GMT).                                                                                                                         	|
# |     <a href=" https://developer.ebay.com/DevZone/shopping/docs/CallRef/GetItemStatus.html"><code>GetItemStatus</code></a>                             	|     This call is used to get   the current status of up to 20 listings and to retrieve information of   listings status, fixed price, and scheduled end time of listing. However, it   returns limited data.    	|
# |     <a href=" https://developer.ebay.com/DevZone/shopping/docs/CallRef/GetMultipleItems.html "><code>GetMultipleItems</code></a>                      	|     Gets visible information on   a listing’s View Item page, such as title and prices .                                                                                                                        	|
# |     <a href=" https://developer.ebay.com/DevZone/shopping/docs/CallRef/GetShippingCosts.html "><code>GetShippingCosts</code></a>                      	|     Retrieves all shipping   types of an item, including flat-rate and calculated, to a specified   destination country and postal code.                                                                        	|
# |     <a href=" https://developer.ebay.com/DevZone/shopping/docs/CallRef/GetSingleItem.html"><code>GetSingleItem</code></a>                             	|     Shows the general public   information on the view item (title, description, basic price information,   etc.)                                                                                               	|
# |     <a href=" https://developer.ebay.com/DevZone/shopping/docs/CallRef/GetUserProfile.html "><code>GetUserProfile</code></a>                          	|     Returns public user   information based on the specified user ID, including the feedback score.                                                                                                             	|
# 	
# 
# Understanding call limits is an important aspect when collecting data. The Finding API limits the number of API calls developers can make to 5000 in a 24 hour period. The 24 hour time frame resets itself at 12:00 a.m. PST. We use this time frame to collect data on a daily basis. As we will discuss in Chapter 3, our recursive Slurm script allows us to automatically collect data. The configuration of our recursive script allows us to collect data on a daily basis, while remaining within the 5000 call limit. This maximizes the amount of data collected each day.
# 
# As a brief overview, an API call is the application's operation to process the request for details of a particular product (Remember that the intermediary - aka the API- seeks and delivers the information). The API receives the calls according to an index that allows them to receive the requested information. More information about call limits across different APIs can be found on eBay’s developer’s programs website. There, users will find the API's user guide and information on how to "make a call” across all APIs.  
# 
# In terms of collecting data across categories within a specific timeframe, there are several key parameters that one would include in the Finding API call to get the corresponding data. This can be understood as the “input” of accessing the data of interest from the Finding API/ To account for the different categories of interest, a call will be made for each of the categories. To account for specific timeline of data collection, a time parameter will also be included. In the case of this project, the timeframe accounted for a 24 hour time period and the categories that pertain to illicit exchange. Details about the code and implementation is discussed in chapter 3. 
# 
# The “output” from the Finding API are various features of interest. The key variables we extracted as listed in the data description section below including item ID, product title, country, and price. These features are outputted as a JSON format, so we convert this to a dataframe to format the data in an intuitive format. Further, instruction on cleaning this output to fit in a dataframe will be discussed in the next chapter. More details about the Finding API can be found  <a href=" https://developer.ebay.com/devzone/finding/CallRef/findItemsByCategory.html">here</a>.
# 
# While the Finding API allows us to get a lot of information regarding the listing by filtering through categories of interest, the Shopping API allows us to use unique item IDs to get more data about these listings. We are using both the Finding API and Shopping API to get data that pertains to the project. One of the important features that is outputted from the Finding API. The item ids in turn becomes the input for the Shopping API. This allows us to limit data collected from the Shopping API to listing we already decided — based on category — that are important from the Finding API. 
# 
# Similar to the Finding API, the Shopping API also contains different calls that make for accessing data based on different inputs. We found two calls from the Shopping API that could have given us the same variables of interest but at different scales. The <code>GetSingleItem</code> call and the <code>GetMultipleItems</code> call both output the same features that would supplement the features we obtained from the Finding API. The Shopping API also has a call limit of **5000 calls per 24 time period** (starting at 12:00 a.m. PST). This call limit is a large motivator of why we implemented the <code>GetMultipleItems</code> call over the <code>GetSingleItem</code> call. While only one item id could be implemented in the <code>GetSingleItem</code> call for each time, one could input up to 20 item ids for a single <code>GetMultipleItems</code> call. This would allow us to maximize the number of observations we get in a single day. There are sections in chapter 3 where we break down how to subset lists of 20 items, so that we can implement the <code>GetMultipleItems</code> call. 
# 
# To integrate the data we collect from the Finding API to the Shopping API, we input item IDs  into our <code>GetMultipleItem</code> call. After inputting item IDs as a parameter, we will be able to extract relevant data into a dataframe. Similar to the Finding API, the default output is not a dataframe, so we have to perform some data processing and data cleaning. The details of cleaning this will be discussed in the next chapter. 
# 
# The “output” from the Shopping API are features of interest that supplement the data we collect from the Finding API. The key variables we extracted as listed in the data description section below. More information about the <code>GetMultipleItems</code> call from the Shopping API can be found <a href="https://developer.ebay.com/Devzone/shopping/docs/CallRef/GetMultipleItems.html">here</a>.
# 

# ### **Categories** <a class="anchor" id="section_2_2_2"></a>
# 
# Categories are the first step to decide where to search for illicit goods. More generally, categories allow one to narrow down on the marketplaces and types of listings that are in the scope of the project. To narrow down on categories, it is first important to communicate and understand the research goals. It is also important to understand the structure of eBay categories. In this section, we will discuss how we narrowed down on categories, the structure of eBay’s categories, the implementation of categories, and additional tools. 
# 
# After having an initial meeting with stakeholders to understand their project goals, we decided that eBay categories are the most intuitive place to start looking for illicit cultural goods. Since eBay is a large online marketplace, they have listings — such as electronics, toys, and clothes — that are not relevant to our project goals. Thus, we narrowed our search to specific categories that might be of interest including antiques, art, coins & paper money. 
# 
# eBay’s categories all have a corresponding category ID. Categories also exist in a nested structure. To understand the relationship between categories, each category has three parameters associated with the category name: category id, parent, and leaf. The category id is an unique identifier for each category. This is a numerical id that is consistent throughout eBay. However, category ids might change on a rare occasion if eBay deems that category to be growing/deprecating. At the end of this section, we provide where eBay updates its users about categories. eBay sellers and users alike use categories to identify goods that are important to them. The parent parameter identifies whether the specific category is a main category. A parent category means that category does not belong to any larger encompassing category. This category may or may not have subcategories. A parent category is identified by eBay with a “-1”. The leaf parameter identifies whether that category does not have any more subcategories for expansion. If a category is identified as a leaf category, there are no smaller categories belonging to that one category. These parameters help identify unique categories, and organize the categories in their nested structure. 
# 
# For the scope of this project, we narrowed down on categories that might have listings that are illicit. We narrowed down on the categories from meetings with our sponsors. We use these categories and their corresponding IDs as our initial input to the Finding API. By going through each category, we are able to get data from categories that interest us. While each item can theoretically belong in many categories, when we extract data for each item, they are associated with a primary category/category ID. This means that when parsing through eBay listings with categories, there will be no duplicate listings across different categories. A complete table of categories and corresponding category identifiers that we use are below. We also included links to resources to better understand the structure of categories, and category updates. Please view **Appendix A** for a table of all categories used in this research. 
# 
# 
# Resources for categories:
# -	<a href="https://www.isoldwhat.com/ "> Third party website to understand categories </a>
# -	<a href="https://pages.ebay.com/sellerinformation/news/categorychanges.html "> eBay’s description and updates of categories </a>
# 

# ### **Data Description**
# 
# The following table are features of interest extracted from the Finding and Shopping API. The table contains the feature name, the data type, and a brief description. The data pipeline that we define in this documentation gathers these features. Changes can be made to the architecture to gather more information. 
# 
# In this work, said features of interest include an item’s price, condition, specifics, and the location of the seller. We believe these item features would be useful in a network analysis because they could be indicative of a network of buyers and sellers. The average price in a category demonstrates what the typical asking price in that network is. The item condition could be related to the price, or even be a trademark for high quality collectors. Item specifics is a detailed description of the item that the seller uses, and it could be assumed that re-listed items would use the same description - allowing researchers to follow a specific item throughout the network. Lastly, the location of a listing helps researchers visualize where the network lives in the global market.
# 
# The following dictionary summarizes the listed categories of the eBay <a href="https://developer.ebay.com/Devzone/shopping/docs/Concepts/ShoppingAPIGuide.html" target="_blank">Shopping API</a> and the <a href="https://developer.ebay.com/DevZone/finding/CallRef/index.html"  target="_blank">Finding API</a>. Although most categories used here come from the Shopping API, some of those categories must be interpreted using the Finding API. See more in-depth document of the features available from eBay's various <a href="https://developer.ebay.com/docs" target="_blank">APIs</a>.
# 
# We have divided our dictionary into two parts: the first part presents the different features obtained from the application, and the second shows a visual display of how we organized the SQL schema.
# 
# The first section uses a tabular data, or spreadsheet, to help users identify the type of data, its description, and the source of the data they are looking for. Note that eBay documentation provides a broad classification of <a href="https://developer.ebay.com/devzone/shopping/docs/CallRef/types/simpletypes.html" target="_blank">schema types</a> - string, dateTime, integer, among others. 
# 
# As the following table shows, each feature corresponds to the type of data, its description, and source:
# 
# *Table 5.* Features, data types and their descriptions 
# 
# |     Feature             |     Description                                                                                                                                                                                    |     Type             |     API Source             |
# |-------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------|----------------------------|
# |     Item_ID             |     ID that   uniquely recognizes the item listing. eBay generates this ID when an item is   listed. ID values are unique across all eBay listings. They are typically   9-12 digits in length.    |     String           |     Finding,   Shopping    |
# |     Product_Title       |     Item name as   it appears in the listing title, or in the search and browse results.                                                                                                           |     String           |     Finding,   Shopping    |
# |     CategoryID          |     ID that   uniquely identifies the category associated with the item listing. If the   listing is nested in a sub-category, the CategoryID will be correlated to   that sub-category’s ID.      |     String           |     Shopping               |
# |     Price               |     A listing's   current price converted to US dollars.                                                                                                                                           |     Integer          |     Finding                |
# |     Item_Condition      |     A list   showing the name and unique ID of the item’s condition.                                                                                                                               |     String (List)    |     Finding                |
# |     Listing_Time        |     Time stamp   eBay records when the listing is made available. This value is returned in   GMT, the ISO 8601 date, and time format (YYYY-MM-DDTHH:MM:SS.SSSZ).                                  |     dateTime         |     Finding                |
# |     Item_Specifics      |     Item   specifics key-value pairs - if they exist - for a listing. This varies   depending on the listing and listing category.                                                                 |     Dictionary       |     Shopping               |
# |     Seller_ID           |     Encrypted ID   that identifies unique sellers. Encoded with a hash code.                                                                                                                       |     String           |     Shopping               |
# |     Country             |     Two-letter   ISO 3166 country code to indicate the country where the item is located   (e.g., “US” for the United States or “GB” for the United Kingdom)                                       |     String           |     Finding                |
# |     Zip_Code            |     The postal   code where the item is listed. Field is returned only if a postal code has   been specified by the seller and is anonymized when returned via the API.                            |     String           |     Finding                |
# |     Image_url           |     The URL of a   specific listing on eBay. The returned URL is optimized to support search and   to make items easier to find via internet search engines.                                       |     String (URL)     |     Finding                |
# |     SKU                 |     Unique SKU   (Stock Keeping Unit), which is an identifier for items for sale . This   identifier is for the object, not the listing.                                                           |     String           |     Shopping               |

# ### **eBay’s Third-Party Personal Deletion Policy** 
# As of September 15, 2021, eBay’s Developer’s Program requires users to be in compliance with their marketplace account deletion notification system. This requires users of eBay’s API to set up a notification that alerts them to delete personal data relevant to listings that have been taken down. Personal data is not clearly defined, so after research, we narrowed down on a definition of personal data that we believe is in compliance with this policy. Personal data in this scenario is data that can identify a particular person who listed the item. Some examples of personal data include country, zip code, and the personal username of the lister. We understand the need to protect people’s privacy and personal data online, so we were happy to comply. However, since we want to identify unique listers on eBay for the scope of our project, we needed to find a way to encrypt this personal data. We arrived at a solution that encrypts unique lister usernames. The code we used to encrypt can be found in Chapter 3. After encryption, there is no way for the usernames to be decrypted to identify the user.  We believe that this was the best solution to keep in compliance with eBay while still being able to form a network for our project. More information about complying with the marketplace account deletion from eBay can be found <a href="https://developer.ebay.com/marketplace-account-deletion"> here</a>.
# 
# #### **Understanding the term “Personal data”** 
# 
# To comply with <a href="https://developer.ebay.com/marketplace-account-deletion" target="_blank">eBay’s personal data deletion</a> policies, our team researched the meaning behind “Personal Data” and assessed its application. Our findings suggest that there is no single definition of “personal data” that assures us how the company will interpret its privacy and personal data policy. The law that appears to apply more closely to our project exists in the State of California, which distinguishes between “Personal information” and “sensitive personal information.”  
#  
# By way of information, and without suggesting that what we present here can be taken as legal advice, we offer some highlights of our research on the subject below.
# 
# 
# #### **Personal Data under Federal Regulations** 
# 
# According to experts, there is no single data protection legislation in the United States. Instead, hundreds of laws regulate the use of personal data at both the federal and state levels. To complicate matters further, several federal data protection laws are sector-specific or focus on data types.  Consequently, “The definition of <a href="https://iclg.com/practice-areas/data-protection-laws-and-regulations/usa" target="_blank">personal information</a> in the U.S. is not uniform across all states or all regulations.”   Although there isn’t a plenary data protection regulation at the federal level, the U.S. Federal Trade Commission (FTC) “often sets the tone on <a href="https://iclg.com/practice-areas/data-protection-laws-and-regulations/usa" target="_blank">federal privacy and data security issues</a>.”
#  
# According to a source, the FTC currently considers <a href="https://www.dlapiperdataprotection.com/index.html?t=definitions&c=US" target="_blank">personal data</a> “information that is linked or reasonably linkable to a specific individual, which could include I.P. addresses and device identifiers, as personal data.”  
#  
# State breach notification laws and data security laws typically define personal information narrowly, focusing on more sensitive categories of information (“sensitive personal data”). Generally, personal health data, financial data, creditworthiness data, student data, biometric data, personal information collected online from children under 13, and information that can be used to carry out identity theft or fraud are considered sensitive. This category can also include social security numbers and other government identifiers, credit card and financial account numbers, passwords and user credentials, health or medical information, insurance I.D., digital signatures, and biometrics.
# 
# #### **California’s Personal Data Laws** 
# 
# eBay’s recent changes to its internal policies have been triggered by legislation recently passed in its home state California. Two pieces of legislation are relevant: the California Consumer Privacy Act (CCPA) and the recently enacted California Privacy Rights Act (CPRA). Regarding the definition of personal information, the CCPA defines it as any information *“that identifies, relates to, describes, is reasonably capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular consumer or household.”* 
#  
# In turn, the CPRA creates a new category of personal information – “sensitive personal information,” which provides consumers with a new right to limit the use and disclosure of such information. Additionally, businesses must include specific disclosures on their sensitive personal information collection and use practices. The <a href="https://www.orrick.com/en/Practices/CPRA" target="_blank">CPRA</a> defines sensitive personal information as consumer’s social security, ethnicity, geolocation, etc.
# 
# 
# Further, eBay’s policy refers to the broader concept of “personal data”.  In order to stay in compliance with this broad definition, we do not keep personal information for marketplaces and listings including and not limited to seller and marketplace identifiers. We comply with this by removing and/or encrypting any of these characteristics associated with an individual seller. We follow California’s definition of “personal data” that provides that the primary criterion for determining whether this protection covers a type of information is its ability to reasonably identify, relate to, describe, or be associated with a particular consumer or household. The features we collect do not contain any information pertaining to the seller, and instead focus on the characteristics of the goods.
# 
# 

# #### **Ethical Implications** <a class="anchor" id="section_2_3_4"></a>
# 
# When building the data pipeline, we face the ethical dilemmas of the preservation of individual data. The implication of storing an individual's data stems from eBay’s marketplace account deletion notification update in September 2021. As discussed in the Personal Data section, this means that for every marketplace (seller’s marketplace or online storefront) that was deleted, all personal seller data that came along that marketplace must be deleted as well. This implication can be looked at from the perspective of multiple stakeholders including eBay as a corporation, seller’s, and researchers using eBay’s developer’s program to access this data. 
# 
# eBay as a corporation wants to protect their user’s personal privacy. This is discussed in the previous section as they implement rules that are broad enough to comply with regulations across state borders. From a utilitarian perspective, in the short term, sellers will likely suffer from an overall decrease in happiness due to their private information being used without their knowledge/consent in our research. In the long run, sellers will benefit from increased trust with their buyers due to a safer online antiquities market. Removal of competitive sellers partaking in the illicit trade will also create a more fair bidding environment. For researchers, keeping seller data will allow us to conduct rigorous network analysis, and provide the foundational framework necessary to begin to piece together the illicit trade market. This will improve research efforts in an area where big data collection has not been greatly explored yet. This research could assist policy-makers to map and understand the market vulnerabilities exploited and created in an online setting. 
# 
# The choices made in building this data pipeline complies with eBay’s rules with keeping other stakeholders in mind. Beyond building an automated data pipeline, we note the metadata and other implications of working with real world data. As a result, this pipeline presents an opportunity to inform others about data ethics, while making sure data science is performed in a fair manner. 
# 
